name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jalankan Script
        run: bash bot-info-tiktok.sh
